---
cidr_networks:
  container: 10.38.0.0/16
  tunnel: 10.39.0.0/16
  storage: 10.43.0.0/16

used_ips:
  - "10.38.1.1,10.38.4.255"
  - "10.39.1.1,10.39.4.255"
  - "10.43.1.1,10.43.4.255"

global_overrides:
  internal_lb_vip_address: 10.38.1.1
  external_lb_vip_address: west-1.cloud.snic.se
  tunnel_bridge: "br-vxlan"
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "eth1"
        ip_from_q: "container"
        type: "raw"
        group_binds:
          - all_containers
          - hosts
        is_container_address: true
        is_ssh_address: true
    - network:
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        container_mtu: "9000"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "1:1000"
        net_name: "vxlan"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth11"
        type: "vlan"
        range: "2000:3000"
        net_name: "vlan"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        ip_from_q: "storage"
        type: "raw"
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute
#          - radosgw
###
### Infrastructure
###

# galera, memcache, rabbitmq, utility
shared-infra_hosts:
  cirrus10:
    ip: 10.38.1.170
  cirrus11:
    ip: 10.38.1.171
  cirrus12:
    ip: 10.38.1.172

# repository (apt cache, python packages, etc)
repo-infra_hosts:
  cirrus10:
    ip: 10.38.1.170
  cirrus11:
    ip: 10.38.1.171
  cirrus12:
    ip: 10.38.1.172

# load balancer
# Ideally the load balancer should not use the Infrastructure hosts.
# Dedicated hardware is best for improved performance and security.
haproxy_hosts:
  cirrus10:
    ip: 10.38.1.170
  cirrus11:
    ip: 10.38.1.171
  cirrus12:
    ip: 10.38.1.172

# rsyslog server
log_hosts:
  cirrus12:
    ip: 10.38.1.172

###
### OpenStack
###
os-infra_hosts:
  cirrus10:
    ip: 10.38.1.170
  cirrus11:
    ip: 10.38.1.171
  cirrus12:
    ip: 10.38.1.172

# keystone
identity_hosts:
  cirrus10:
    ip: 10.38.1.170
  cirrus11:
    ip: 10.38.1.171
  cirrus12:
    ip: 10.38.1.172

# cinder api services
storage-infra_hosts:
  cirrus10:
    ip: 10.38.1.170
  cirrus11:
    ip: 10.38.1.171
  cirrus12:
    ip: 10.38.1.172

# glance
# The settings here are repeated for each infra host.
# They could instead be applied as global settings in
# user_variables, but are left here to illustrate that
# each container could have different storage targets.

# nova api, conductor, etc services
compute-infra_hosts:
  cirrus10:
    ip: 10.38.1.170
  cirrus11:
    ip: 10.38.1.171
  cirrus12:
    ip: 10.38.1.172

# heat
orchestration_hosts:
  cirrus10:
    ip: 10.38.1.170
  cirrus11:
    ip: 10.38.1.171
  cirrus12:
    ip: 10.38.1.172

# horizon
dashboard_hosts:
  cirrus10:
    ip: 10.38.1.170
  cirrus11:
    ip: 10.38.1.171
  cirrus12:
    ip: 10.38.1.172

# neutron server, agents (L3, etc)
network_hosts:
  cirrus10:
    ip: 10.38.1.170
  cirrus11:
    ip: 10.38.1.171
  cirrus12:
    ip: 10.38.1.172

# ceilometer (telemetry data collection)
metering-infra_hosts:
  cirrus10:
    ip: 10.38.1.170
  cirrus11:
    ip: 10.38.1.171
  cirrus12:
    ip: 10.38.1.172

# aodh (telemetry alarm service)
#metering-alarm_hosts:
#  cirrus10:
#    ip: 10.38.1.170
#  cirrus11:
#    ip: 10.38.1.171
#  cirrus12:
#    ip: 10.38.1.172

# gnocchi (telemetry metrics storage)
#metrics_hosts:
#  cirrus10:
#    ip: 10.38.1.170
#  cirrus11:
#    ip: 10.38.1.171
#  cirrus12:
#    ip: 10.38.1.172

# nova hypervisors
compute_hosts:
  cirrus101-1:
    ip: 10.38.3.101
  cirrus101-2:
    ip: 10.38.3.102
  cirrus101-3:
    ip: 10.38.3.103
  cirrus101-4:
    ip: 10.38.3.104
  cirrus123-1:
    ip: 10.38.3.105
  cirrus123-2:
    ip: 10.38.3.106
  cirrus123-3:
    ip: 10.38.3.107
  cirrus123-4:
    ip: 10.38.3.108

# ceilometer compute agent (telemetry data collection)
#metering-compute_hosts:
#  cirrus101-1:
#    ip: 10.38.3.101
#  cirrus101-2:
#    ip: 10.38.3.102
#  cirrus101-3:
#    ip: 10.38.3.103
#  cirrus101-4:
#    ip: 10.38.3.104

# rados gw hosts
#radosgw_hosts:
#  cirrus10:
#    ip: 10.38.1.170
#  cirrus11:
#    ip: 10.38.1.171
#  cirrus12:
#    ip: 10.38.1.172  

# suprauth containers
suprauth-infra_hosts:
  cirrus10:
    ip: 10.38.1.170
  cirrus11:
    ip: 10.38.1.171
  cirrus12:
    ip: 10.38.1.172

# cinder volume hosts (NFS-backed)
# The settings here are repeated for each infra host.
# They could instead be applied as global settings in
# user_variables, but are left here to illustrate that
# each container could have different storage targets.
storage_hosts:
  cirrus10:
    ip: 10.38.1.170
    container_vars:
      cinder_backends:
        limit_container_types: cinder_volume
        rbd:
          #volume_group: ssc-cinder-volumes
          volume_driver: cinder.volume.drivers.rbd.RBDDriver
          rbd_pool: ssc-cinder-volumes-md
          rbd_ceph_conf: /etc/ceph/ceph.conf
          rbd_flatten_volume_from_snapshot: 'false'
          rbd_max_clone_depth: 5
          rbd_store_chunk_size: 4
          rados_connect_timeout: -1
          volume_backend_name: rbd
          rbd_user: cinder
          rbd_secret_uuid: "{{ cinder_ceph_client_uuid }}"
  cirrus11:
    ip: 10.38.1.171
    container_vars:
      cinder_backends:
        limit_container_types: cinder_volume
        rbd:
          #volume_group: ssc-cinder-volumes
          volume_driver: cinder.volume.drivers.rbd.RBDDriver
          rbd_pool: ssc-cinder-volumes-md
          rbd_ceph_conf: /etc/ceph/ceph.conf
          rbd_flatten_volume_from_snapshot: 'false'
          rbd_max_clone_depth: 5
          rbd_store_chunk_size: 4
          rados_connect_timeout: -1
          volume_backend_name: rbd
          rbd_user: cinder
          rbd_secret_uuid: "{{ cinder_ceph_client_uuid }}"
  cirrus12:
    ip: 10.38.1.172
    container_vars:
      cinder_backends:
        limit_container_types: cinder_volume
        rbd:
          #volume_group: ssc-cinder-volumes
          volume_driver: cinder.volume.drivers.rbd.RBDDriver
          rbd_pool: ssc-cinder-volumes-md
          rbd_ceph_conf: /etc/ceph/ceph.conf
          rbd_flatten_volume_from_snapshot: 'false'
          rbd_max_clone_depth: 5
          rbd_store_chunk_size: 4
          rados_connect_timeout: -1
          volume_backend_name: rbd
          rbd_user: cinder
          rbd_secret_uuid: "{{ cinder_ceph_client_uuid }}"
